### ISSUE TITLE
Manual on how to use in another module

### ISSUE THREAD

**Issue by haadcode** [thiagodelgado111/eslint-config-orbitdb#4]
Really happy we have this now! 😍 

I wanted to add it to https://github.com/orbitdb/orbit-db-identity-provider to get in to use quickly, but I realized there's no instructions how to use it in a module. Nothing ever being obvious to a user, it'd be best to document each step and command in detail on how to add this (and linting and other tools, if assumed to be installed) to a project.

**Comment by RichardLitt** [comment]
I think this is fulfilled by orbitdb/welcome#40.
