### ISSUE TITLE
Rename to eslint-config

### ISSUE THREAD

**Issue by RichardLitt** [thiagodelgado111/eslint-config-orbitdb#8]
This package is scoped as `@orbitdb/eslint-config`. I don't think it needs to have orbitdb in the title, twice.

**Comment by haadcode** [comment]
Makes sense if we go down the road of namespacing them 👍

**Comment by haadcode** [comment]
As this repo has been deprecated, closing the the issue.

**Comment by RichardLitt** [comment]
Thanks @haadcode.
